version: '3.5'

services:
    lumen:
      ports:
        - "8000:8000"
      volumes:
        - .:/var/www/api-transfers
        - /var/www/api-transfers/vendor/
      build: .
      command: php -S lumen:8000 -t public
      restart: always
      depends_on:
        - db
    db:
        image: mysql:8.0
        container_name: mysqldb
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: transactions_db
        command: --default-authentication-plugin=mysql_native_password
        ports:
          - "3306:3306"
volumes:
  mysql-data:
